export {default as Article } from "./Article"
export {default as BgImage} from "./BgImage"
export {default as Cita} from "./Cita"
export {default as Header} from "./Header"
export {default as Resume} from "./Resume"
export {default as Sidebar} from "./Sidebar"
export {default as Title} from "./Title"
export {default as TextMin} from "./TextMin"
export {default as TextAll} from "./TextAll"
export {default as Form} from "./Form"
export {default as Posts} from "./Posts"
export {default as Footer} from "./Footer"
export {default as SecPost} from "./SecPost"